Classification


In [1]:
import pandas as pd
import tensorflow as tf

In [17]:
from google.colab import files
uploadFile = files.upload()

Saving iris.csv to iris.csv


In [18]:
iris = pd.read_csv('iris.csv')
iris.columns = ['petal_length', 'petal_width', 'calyx_length', 'calyx_width', 'class']
print(iris.columns)
iris.head()

Index(['petal_length', 'petal_width', 'calyx_length', 'calyx_width', 'class'], dtype='object')


petal_length  petal_width  calyx_length  calyx_width   class
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa

In [7]:
# onehot-encoding
incoding = pd.get_dummies(iris)
print(incoding.columns)
incoding.head()

Index(['petal_length', 'petal_width', 'calyx_length', 'calyx_width',
       'class_setosa', 'class_versicolor', 'class_virginica'],
      dtype='object')


petal_length  petal_width  calyx_length  calyx_width  class_setosa  \
0           5.1          3.5           1.4          0.2             1   
1           4.9          3.0           1.4          0.2             1   
2           4.7          3.2           1.3          0.2             1   
3           4.6          3.1           1.5          0.2             1   
4           5.0          3.6           1.4          0.2             1   

   class_versicolor  class_virginica  
0                 0                0  
1                 0                0  
2                 0                0  
3                 0                0  
4                 0                0

In [8]:
# independent value (inde_val), dependent value (de_val)
inde_val = incoding[['petal_length', 'petal_width', 'calyx_length', 'calyx_width']]
de_val = incoding[['class_setosa', 'class_versicolor','class_virginica']]
print(inde_val.shape, de_val.shape)

(150, 4) (150, 3)


In [9]:
# model
X = tf.keras.layers.Input(shape=[4])
Y = tf.keras.layers.Dense(3,activation='softmax')(X)
model = tf.keras.models.Model(X,Y)
model.compile(loss='categorical_crossentropy',
             metrics = 'accuracy')

In [10]:
model.fit(inde_val, de_val, epochs=200)

Epoch 1/200
5/5 [==============================] - 1s 3ms/step - loss: 0.7495 - accuracy: 0.6800
Epoch 2/200
5/5 [==============================] - 0s 4ms/step - loss: 0.7183 - accuracy: 0.8000
Epoch 3/200
5/5 [==============================] - 0s 3ms/step - loss: 0.7013 - accuracy: 0.8200
Epoch 4/200
5/5 [==============================] - 0s 3ms/step - loss: 0.6911 - accuracy: 0.8533
Epoch 5/200
5/5 [==============================] - 0s 3ms/step - loss: 0.6839 - accuracy: 0.8667
Epoch 6/200
5/5 [==============================] - 0s 3ms/step - loss: 0.6774 - accuracy: 0.8467
Epoch 7/200
5/5 [==============================] - 0s 3ms/step - loss: 0.6705 - accuracy: 0.8533
Epoch 8/200
5/5 [==============================] - 0s 3ms/step - loss: 0.6653 - accuracy: 0.8400
Epoch 9/200
5/5 [==============================] - 0s 4ms/step - loss: 0.6601 - accuracy: 0.8400
Epoch 10/200
5/5 [==============================] - 0s 3ms/step - loss: 0.6559 - accuracy: 0.8200
Epoch 11/200
5/5 [===========

In [14]:
print(model.predict(inde_val[0:5]))
print(de_val[0:5])


1/1 [==============================] - 0s 93ms/step
[[0.9507736  0.04509392 0.00413248]
 [0.9177797  0.07502948 0.00719078]
 [0.93691325 0.05689389 0.00619286]
 [0.8968237  0.09207585 0.01110046]
 [0.9527953  0.04295069 0.00425395]]
   class_setosa  class_versicolor  class_virginica
0             1                 0                0
1             1                 0                0
2             1                 0                0
3             1                 0                0
4             1                 0                0


In [15]:
print(model.predict(inde_val[-5:]))
print(de_val[-5:])


1/1 [==============================] - 0s 28ms/step
[[0.00616358 0.26690602 0.7269304 ]
 [0.00644598 0.38268057 0.61087346]
 [0.00686297 0.3427295  0.65040755]
 [0.00353035 0.19233096 0.8041387 ]
 [0.00617717 0.3385209  0.6553019 ]]
     class_setosa  class_versicolor  class_virginica
145             0                 0                1
146             0                 0                1
147             0                 0                1
148             0                 0                1
149             0                 0                1


In [16]:
model.get_weights()

[array([[ 0.51559967,  0.10080236, -0.51793677],
        [ 1.2253325 ,  0.3023457 ,  0.46026334],
        [-1.5836842 ,  0.37320286,  0.65361786],
        [-0.29308718, -0.49176422,  1.124983  ]], dtype=float32),
 array([ 0.52844864,  0.12593356, -0.37700933], dtype=float32)]